package reporteincidente.Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import reporteincidente.Entidades.Cliente;
import reporteincidente.Entidades.Complejidad;
import reporteincidente.Entidades.Especialidad;
import reporteincidente.Entidades.Incidente;
import reporteincidente.Entidades.Servicio;
import reporteincidente.Entidades.Tecnico;
import reporteinicidente.Repositorio.ClienteJpaController;
import reporteinicidente.Repositorio.IncidenteJpaController;
import reporteinicidente.Repositorio.TecnicoJpaController;

public class ABMIncidenteFrame extends javax.swing.JInternalFrame {

    List<Cliente> clienteAux = new ArrayList<>();
    List<Tecnico> listaTecnicos = new ArrayList<>();

    /**
     * Creates new form ABMIncidenteFrame
     */
    public ABMIncidenteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCuit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCboxServicios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTxtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtRazonSocial = new javax.swing.JTextField();
        jTxtCodigo = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCboxTecnicos = new javax.swing.JComboBox<>();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setTitle("Alta Incidente");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Cuit cliente: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Servicios contratados:");

        jCboxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboxServiciosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Descripcion del problema:");

        jLabel4.setText("Razon Social:");

        jLabel5.setText("Codigo:");

        jTxtRazonSocial.setEditable(false);

        jTxtCodigo.setEditable(false);

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jLabel6.setText("Tecnicos Disponibles:");

        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jCboxTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtDescripcion))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jCboxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jBtnBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnConfirmar)
                .addGap(35, 35, 35)
                .addComponent(jBtnCancelar)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCboxServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCboxTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        long codigo;
        if (!jTxtCuit.getText().isEmpty()) {
            ClienteJpaController controlCliente = new ClienteJpaController();
            codigo = Long.parseLong(jTxtCuit.getText());
            clienteAux = controlCliente.buscarPorCuit(codigo);
            if (!clienteAux.isEmpty()) {
                jTxtCodigo.setText(clienteAux.get(0).getId() + "");
                jTxtRazonSocial.setText(clienteAux.get(0).getRazonSocial());
                List<Servicio> listaServicio = new ArrayList<>();
                listaServicio = clienteAux.get(0).getServicios();
                for (Servicio servicio : listaServicio) {
                    jCboxServicios.addItem(servicio);
                }

            } else {
                JOptionPane.showMessageDialog(this, "CUIT NO EXISTE");
            }
        } else {
            JOptionPane.showMessageDialog(this, "INGRESAR CUIT");
        }

    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jCboxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboxServiciosActionPerformed

        jCboxTecnicos.removeAllItems();
        DefaultComboBoxModel<Servicio> modelo = (DefaultComboBoxModel<Servicio>) jCboxServicios.getModel();

        Servicio servicio = (Servicio) jCboxServicios.getSelectedItem();

        Especialidad unaEspecialidad = new Especialidad();
        unaEspecialidad = servicio.getEspecialidad();
        TecnicoJpaController controlTecnicos = new TecnicoJpaController();
        listaTecnicos = controlTecnicos.findTecnicoEntities();
        for (Tecnico listaTecnico : listaTecnicos) {
            List<Especialidad> listaEsp = new ArrayList<>();
            listaEsp = listaTecnico.getEspecialidad();
            for (Especialidad especialidad : listaEsp) {
                if (especialidad.getId() == servicio.getId()) {
                    jCboxTecnicos.addItem(listaTecnico);
                }
            }

        }


    }//GEN-LAST:event_jCboxServiciosActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed

        LocalDate hoy = LocalDate.now();
        if ((!jTxtCuit.getText().isEmpty())&&(!clienteAux.isEmpty())&&(!listaTecnicos.isEmpty())) {
            Incidente unIncidente = new Incidente();
            unIncidente.setEstado(true);
            unIncidente.setDescripcion(jTxtDescripcion.getText());
            unIncidente.setFechaInicio(Date.from(hoy.atStartOfDay(ZoneId.systemDefault()).toInstant()));
            unIncidente.setCliente(clienteAux.get(0));
            unIncidente.setTecnico(listaTecnicos.get(0));
            List<Especialidad> listaEspecialidad=new ArrayList<>();
            listaEspecialidad=listaTecnicos.get(0).getEspecialidad();
            Complejidad nivelComplejidad=new Complejidad();
            Servicio elServicio=new Servicio();
            elServicio= (Servicio) jCboxServicios.getSelectedItem();
            for (Especialidad especialidad : listaEspecialidad) {
                if (especialidad.getServicio().getId()==(elServicio.getId())){
                    nivelComplejidad.setNivel(especialidad.getComplejidad());
                    JOptionPane.showMessageDialog(this, "Tiempo estimado de resolucion: "+ nivelComplejidad.toString());
                    break;
                }
            }
            IncidenteJpaController controlIncidente=new IncidenteJpaController();
            controlIncidente.create(unIncidente);
            //EN ESTA PARTE AL TECNICO ASIGNADO ENVIO UN EMAIL CON EL PEDIDO DE RESOLUCION.
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Falta informacion");
        }


    }//GEN-LAST:event_jBtnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JComboBox<Servicio> jCboxServicios;
    private javax.swing.JComboBox<Tecnico> jCboxTecnicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtCuit;
    private javax.swing.JTextField jTxtDescripcion;
    private javax.swing.JTextField jTxtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
