/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reporteincidente.Vistas;

/**
 *
 * @author Li Donni
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMABMCliente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMABMTecnicos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMABMEspecialidad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMAltaIncidente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        jMenu1.setText("Clientes");

        jMABMCliente.setText("ABM Cliente");
        jMABMCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMABMClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMABMCliente);

        jMenuItem2.setText("Alta Servicios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tecnicos");

        jMABMTecnicos.setText("ABM Tecnicos");
        jMABMTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMABMTecnicosActionPerformed(evt);
            }
        });
        jMenu2.add(jMABMTecnicos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Especialidad");

        jMABMEspecialidad.setText("ABM Especialidad");
        jMABMEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMABMEspecialidadActionPerformed(evt);
            }
        });
        jMenu3.add(jMABMEspecialidad);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Incidente");

        jMAltaIncidente.setText("Alta De Incidente");
        jMAltaIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAltaIncidenteActionPerformed(evt);
            }
        });
        jMenu4.add(jMAltaIncidente);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");
        jMenuBar1.add(jMenu5);

        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //SALGO DEL PROGRAMA
    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMSalirMouseClicked

    private void jMABMClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMABMClienteActionPerformed
        ABMClienteFrame ventanaCliente = new ABMClienteFrame();
        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        int x = (jEscritorio.getWidth() - ventanaCliente.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - ventanaCliente.getHeight()) / 2;
        ventanaCliente.setLocation(x, y);
    }//GEN-LAST:event_jMABMClienteActionPerformed

    private void jMABMEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMABMEspecialidadActionPerformed
        ABMEspecialidad ventanaCliente = new ABMEspecialidad();
        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        int x = (jEscritorio.getWidth() - ventanaCliente.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - ventanaCliente.getHeight()) / 2;
        ventanaCliente.setLocation(x, y);
    }//GEN-LAST:event_jMABMEspecialidadActionPerformed

    private void jMABMTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMABMTecnicosActionPerformed
        ABMTecnicoFrame ventanaCliente = new ABMTecnicoFrame();
        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        int x = (jEscritorio.getWidth() - ventanaCliente.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - ventanaCliente.getHeight()) / 2;
        ventanaCliente.setLocation(x, y);
    }//GEN-LAST:event_jMABMTecnicosActionPerformed

    private void jMAltaIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAltaIncidenteActionPerformed
        ABMIncidenteFrame ventanaCliente = new ABMIncidenteFrame();
        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        int x = (jEscritorio.getWidth() - ventanaCliente.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - ventanaCliente.getHeight()) / 2;
        ventanaCliente.setLocation(x, y);
    }//GEN-LAST:event_jMAltaIncidenteActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ABMServicioFrame ventanaCliente = new ABMServicioFrame();
        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        int x = (jEscritorio.getWidth() - ventanaCliente.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - ventanaCliente.getHeight()) / 2;
        ventanaCliente.setLocation(x, y);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenuItem jMABMCliente;
    private javax.swing.JMenuItem jMABMEspecialidad;
    private javax.swing.JMenuItem jMABMTecnicos;
    private javax.swing.JMenuItem jMAltaIncidente;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
